openapi: 3.1.0
x-stoplight:
  id: nv3zp697aowmt
info:
  title: shortener-apis
  version: '1.0'
  summary: APIs for the Shortener service
  description: APIs for the shortener service
servers:
  - url: 'http://localhost:3000'
paths:
  '/{linkId}':
    parameters:
      - schema:
          type: string
        name: linkId
        x-go-name: linkID
        in: path
        required: true
    get:
      summary: Redirect to link
      tags:
        - Links
      responses:
        '302':
          description: Found
        '404':
          description: Not Found
      operationId: get-link-by-id
      description: This endpoint redirects to the route that is shortened with this ID
  /api/v1/admin/login:
    post:
      summary: ''
      operationId: login-admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminLoginResponse'
        '401':
          description: Unauthorized
      description: Endpoint for admin login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginRequest'
  /api/v1/links:
    post:
      summary: ''
      operationId: create-new-link
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShortLinkResponse'
      description: Endpoint that creates a new link
      security:
        - JWT:
            - admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShortLinkRequest'
    get:
      summary: ''
      operationId: get-all-links
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLinksResponse'
  '/api/v1/links/{linkId}':
    parameters:
      - schema:
          type: string
        name: linkId
        x-go-name: linkID
        in: path
        required: true
    get:
      summary: Get Link Metrics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLinkMetricsResponse'
      operationId: get-link-metrics
      description: Endpoint for getting the metrics of a shortened link
      security:
        - JWT:
            - admin
    delete:
      summary: Delete link
      operationId: delete-short-link
      responses:
        '204':
          description: No Content
      security:
        - JWT:
            - admin
components:
  schemas:
    AdminLoginRequest:
      title: AdminLoginRequest
      x-stoplight:
        id: g8rl079eb7og3
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AdminLoginResponse:
      title: AdminLoginResponse
      x-stoplight:
        id: 9177pcmac8xb9
      type: object
      properties:
        token:
          type: string
      required:
        - token
    CreateShortLinkRequest:
      title: CreateShortLinkRequest
      x-stoplight:
        id: i3nu9nw80y2qa
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        url:
          type: string
          x-go-name: URL
      required:
        - url
    CreateShortLinkResponse:
      title: CreateShortLinkResponse
      x-stoplight:
        id: xuvczey6mlyiy
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        url:
          type: string
          x-go-name: URL
      required:
        - id
        - url
    GetLinkMetricsResponse:
      title: GetLinkMetricsResponse
      x-stoplight:
        id: 3rth01ewn733o
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        url:
          type: string
          x-go-name: URL
        metrics:
          $ref: '#/components/schemas/LinkMetrics'
      required:
        - id
        - url
        - metrics
    LinkMetrics:
      title: LinkMetrics
      x-stoplight:
        id: yrsqmctmbk6df
      type: object
      properties:
        clicks:
          type: integer
      required:
        - clicks
    GetLinksResponse:
      title: GetLinksResponse
      x-stoplight:
        id: z9i0z71civm2o
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    Link:
      title: Link
      x-stoplight:
        id: 4rinfiezwm23e
      type: object
      properties:
        id:
          type: string
          x-go-name: ID
        url:
          type: string
          x-go-name: URL
      required:
        - id
        - url
  requestBodies: {}
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      description: ''
