openapi: 3.1.0
x-stoplight:
  id: nv3zp697aowmt
info:
  title: shortener-apis
  version: '1.0'
  summary: APIs for the Shortener service
  description: APIs for the shortener service
servers:
  - url: 'http://localhost:3000'
paths:
  '/{linkId}':
    parameters:
      - schema:
          type: string
        name: linkId
        in: path
        required: true
    get:
      summary: Redirect to link
      tags:
        - Links
      responses:
        '302':
          description: Found
        '404':
          description: Not Found
      operationId: get-link-by-id
      description: This endpoint redirects to the route that is shortened with this ID
  /api/v1/admin/login:
    post:
      summary: ''
      operationId: login-admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminLoginResponse'
        '401':
          description: Unauthorized
      description: Endpoint for admin login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginRequest'
components:
  schemas:
    AdminLoginRequest:
      title: AdminLoginRequest
      x-stoplight:
        id: g8rl079eb7og3
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AdminLoginResponse:
      title: AdminLoginResponse
      x-stoplight:
        id: 9177pcmac8xb9
      type: object
      properties:
        token:
          type: string
      required:
        - token
  requestBodies: {}
