// Code generated by "stringer -type=Role -linecomment"; DO NOT EDIT.

package users

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleAdmin-0]
	_ = x[RoleUser-10]
}

const (
	_Role_name_0 = "Admin"
	_Role_name_1 = "User"
)

func (i Role) String() string {
	switch {
	case i == 0:
		return _Role_name_0
	case i == 10:
		return _Role_name_1
	default:
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
